[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 2
solc = "0.8.26"
optimizer = true
optimizer_runs = 100000
evm_version = "cancun"
fs_permissions = [{ access = "read", path = "proofs"}]

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "single"
  tab_width = 4
  wrap_comments = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
